version: '3.7'

services:
  sage:
    image: sagemath/sagemath:9.1
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/sage
    # /usr/local/bin$ cat sage-entrypoint
    # exec sage -n jupyter --no-browser --ip='0.0.0.0' --port=8888 "$@"
    command: ["sage-jupyter"]
 